### ISSUE TITLE
Refactor config loader to compute composite values in software instead of in the YAML

### ISSUE THREAD

**Issue by ByteCommander** [python-discord/bot#206]
Currently some magic happens in the YAML config files that lets you reference other values in the same file. That way you can e.g. concatenate a protocol, domain, subdomain and path to compose a single URL value, like in this snippet:

```yaml
urls:
    # PyDis site vars
    site:        &DOMAIN       "pythondiscord.local:8080"
    site_api:    &API    !JOIN ["api.", *DOMAIN]
    site_paste:  &PASTE  !JOIN ["paste.", *DOMAIN]
    site_schema: &SCHEMA       "http://"

    site_bigbrother_api:                !JOIN [*SCHEMA, *API, "/bot/bigbrother"]
    site_docs_api:                      !JOIN [*SCHEMA, *API, "/bot/docs"]
```

This is nice with a single file, but we have two, `config-default.yml` and a custom `config.yml` to override values from the other. However, as these functions are evaluated when the YAML file is read, and the two files are interpreted sequentially, this means that __you have to always override all values that reference any variable you override__, otherwise those will still contain the value built with the default variable.

For example, when I override the `site` or `protocol` value here, I must copy/paste all of the currently 22 `site_*` values that reference them, even though I don't change anything in those lines. This creates hard to debug problems when some lines referencing my overridden value get changed in the default config, as it has happened with the "hiphopify" endpoint.

I propose that we should __not use any such variables and concatenation functions in the YAML definitions but instead implement such logic in the config loader code__. In case of URLs, if you still want to be able to override e.g. the domain for just a single value instead of all of them, make the loader check if there's just a path specified or whether it includes a domain and only add the missing parts. 

PS: While discussing this in chat, switching the config file format to TOML instead of YAML has been proposed too, but this should be lined out in a separate issue.
