### ISSUE TITLE
Add Pre-Commit dev dependency and .flake8 configuration

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#250]
Related to #211, I'd like to add [pre-commit](https://pre-commit.com/) as a dev dependency to ensure that code is being linted before pushing. Rather than relying on developers to remember to set up either global or local commit hooks (I don't remember), `pre-commit` allows for a standardized configuration that only requires a single additional CLI command when initially setting up the repository.

The addition to the repository would be a `.pre-commit-config.yaml`:
```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
```

And the developer runs
```
pipenv run precommit
```
or
```
pre-commit install
```

In the project directory to setup the hook.

Additionally, I'd like to propose adding a standardized `.flake8` [configuration file](http://flake8.pycqa.org/en/latest/user/configuration.html) to surface the linting configuration across our repositories (See: https://github.com/python-discord/pydis-bot-core/issues/2).
