### ISSUE TITLE
Config variable inheritance in config.yml requires all config values using the vars to be copied across.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#287]
In `yml` files, you can define a certain entry to be a reusable variable, which can be used throughout the rest of the config. Example, `DOMAIN`, `API` and `SCHEMA` below:
```yml
urls:
    site:        &DOMAIN       "pythondiscord.local:8080"
    site_api:    &API    !JOIN ["api.", *DOMAIN]
    site_schema: &SCHEMA       "http://"

    site_bigbrother_api:                !JOIN [*SCHEMA, *API, "/bot/bigbrother"]
    site_docs_api:                      !JOIN [*SCHEMA, *API, "/bot/docs"]
```

Due to this, if we adjust the `site` key's value, `DOMAIN` will change, which means `API` will change, and in order for the new variables to correctly change any other keys that depend on those variables, we will need to copy them into the config file also, even if they don't appear to have changed.

This should be worked around in order to have the inheritance changed so it'll correctly apply variable values to children that aren't in config-default.yml, or simply move the inheritance system to being applied within the script, allowing us to define these parent keys that others depend on without having to add all the children to the config file. This will make the config.yml file more readable at a glance as to what things have been adjusted, and will ensure we don't have any issues where a new child key is introduced in config-default.yml and we forgot to move it over to config.yml since we didn't notice.
